/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [
    {
      type: 'category',
      label: '开始',
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "get_started" }],
      link: {
        type: 'generated-index',
        description: 'Get started with Voxels',
        slug: "get_started",
      },
    },
    {
      type: "category",
      label: "Parcels 地块",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "Parcels" }],
      link: {
        type: 'generated-index',
        slug: "Parcels",
      },
    },
    {
      type: "category",
      label: "Players 玩家",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "Players" }],
      link: {
        type: 'generated-index',
        slug: "Players",
      },
    },
    {
      type: "category",
      label: "Features 功能",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "-Features" }],
      link: {
        type: 'generated-index',
        slug: "-Features",
      },
    },
    {
      type: "category",
      label: "Scripting 脚本",
      collapsed: true,
      collapsible: true,
      items: [{ type: "autogenerated", dirName: "Scripting" }],
      link: {
        type: 'generated-index',
        slug: "Scripting",
      },
    },
  ],
};